spring.application.name=FundooNotes

spring.datasource.url=jdbc:postgresql://localhost:5432/fundoo_notes_db
spring.datasource.username=postgres
spring.datasource.password=root@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=ThisIsMyFundooNotesSecretKeyForJWTAuthentication123456789
jwt.expiration=3600000

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.artemis.mode=embedded

logging.level.com.bridgelabz.fundoo.notes=INFO
logging.file.name=logs/application.log
